import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { AnswerEdge, ContentEdge } from "../framework/parser";
import { Runner } from "../framework/runner";
import styles from "../styles/Home.module.css";

type ContentEdgeWithId = { id: AnswerEdge } & ContentEdge;

const runner = new Runner();

const Home: NextPage = () => {
  const [nodeText, setNodeText] = useState<string>(runner.getCurrentNodeContent());
  const [edgesContent, setEdgesContent] = useState<ContentEdgeWithId[]>([]);

  useEffect(() => {
    const listener = () => {
      setNodeText(runner.getCurrentNodeContent());

      setEdgesContent(
        Object.keys(runner.getCurrentNode().edges).map((edgeId) => ({
          id: edgeId as AnswerEdge,
          ...runner.getEdgeContent(edgeId),
        }))
      );
    }

    runner.setListener(listener);

    listener();

    return () => runner.setListener(() => {});
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{nodeText}</div>

      {edgesContent.map(({ id, long, short }) => (
        <button key={id} onClick={() => runner.makeSelection(id)}>{long}</button>
      ))}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
